/* Generated by package_nanocockpit.py. */
#ifndef PERCEPTION_MODEL_QPARAMS_H
#define PERCEPTION_MODEL_QPARAMS_H

#define PERCEPTION_MODEL_CHANNELS 8
#define PERCEPTION_MODEL_OBSTACLE_CHANNEL 4
#define PERCEPTION_MODEL_INVERSE_RANGE_CHANNEL 5
#define PERCEPTION_MODEL_UNCERTAINTY_CHANNEL 6
#define PERCEPTION_MODEL_GATE_CHANNEL 7
#define PERCEPTION_MODEL_DANGER_THRESHOLD 0.4f

static const float perceptionModelOutputEpsilon = 0.1988997012f;
static const float perceptionModelSpatialOffset[PERCEPTION_MODEL_CHANNELS] = {8.042428835f, 11.11182962f, 11.5725678f, 8.653360231f, 12.78889833f, 7.226821764f, 5.082098348f, 36.62235342f};
static const float perceptionModelLearnedBias[PERCEPTION_MODEL_CHANNELS] = {-5.684194088f, -0.3608348966f, -0.453181088f, -3.457415581f, 0.1745830327f, 1.191730738f, 1.386082292f, -1.406413555f};

static inline float perceptionModelOutputLogit(unsigned char q,
                                               int channel) {
  return q * perceptionModelOutputEpsilon
       - perceptionModelSpatialOffset[channel]
       + perceptionModelLearnedBias[channel];
}

#endif
