/* Runtime controls and diagnostics for the four-direction visual corridor. */
#include "log.h"
#include "param.h"

#include <stdint.h>

extern uint8_t seqAvoidEnable;
extern uint8_t seqAvoidConstraintEnable;
extern uint8_t seqAvoidLogOnly;
extern float seqAvoidConfidenceMin;
extern uint32_t seqAvoidMaxAgeMs;
extern uint32_t seqAvoidDropoutGraceMs;
extern float seqAvoidDroneRadiusM;
extern float seqAvoidTrackingMarginM;
extern float seqAvoidLatencyS;
extern float seqAvoidPerceptionMarginM;
extern float seqAvoidConfidenceGainM;
extern float seqAvoidDefaultOffsetM;
extern float seqAvoidMaxRangeM;
extern float seqAvoidDirectionSafeMinM;
extern uint8_t seqAvoidAverageWindow;
extern float seqAvoidTriggerAverage;
extern float seqAvoidClearAverage;
extern float seqAvoidTriggerM;
extern float seqAvoidActivationEpsM;
extern float seqAvoidReferenceShiftM;
extern float seqAvoidReturnDelayS;
extern float seqAvoidReturnRateMps;
extern uint8_t seqAvoidReturnScanEnable;
extern float seqAvoidReturnScanYawDeg;
extern float seqAvoidReturnScanYawRateDegS;
extern float seqAvoidReturnScanSettleS;
extern uint8_t seqAvoidReturnScanWindow;
extern float seqAvoidReturnScanClearAverage;
extern float seqAvoidReturnScanRetryS;
extern float seqAvoidSideBiasM;
extern float seqAvoidScanGradientM;
extern float seqAvoidScanImprovementM;
extern float seqAvoidScanRetryMinS;
extern float seqAvoidScanRetryMaxS;
extern float seqAvoidCruiseSpeedMps;
extern float seqAvoidCruiseAccelMps2;
extern float seqAvoidBrakingAccelMps2;
extern float seqAvoidSpeedStopMinM;
extern float seqAvoidSpeedResumeMinM;
extern float seqAvoidGoalToleranceM;
extern float seqAvoidSideMinimumM;
extern uint8_t seqAvoidSideVotesRequired;
extern float seqAvoidForwardMinimumM;
extern float seqAvoidForwardStepM;
extern float seqAvoidPassDistanceM;
extern float seqAvoidWaypointToleranceM;
extern uint8_t seqAvoidClearVotesRequired;
extern float seqAvoidMaxLateralM;
extern float seqAvoidProbeProgressM;
extern uint8_t seqAvoidProbeVotesRequired;
extern float seqAvoidMaxPrimalResidual;
extern float seqAvoidMaxDualResidual;
extern uint32_t seqAvoidMaxSolveUs;
extern float seqAvoidSlackPenalty;
extern float seqAvoidDistanceWeight;
extern float seqAvoidGoalWeight;
extern float seqAvoidHysteresisWeight;
extern float seqAvoidDynamicWeight;
extern uint8_t seqAvoidKStart;

extern uint8_t g_seq_valid;
extern uint8_t g_seq_stop;
extern uint8_t g_seq_reliable_mask;
extern int8_t g_seq_chosen;
extern uint8_t g_seq_constraints;
extern uint8_t g_seq_grace;
extern uint32_t g_seq_grace_age_ms;
extern uint32_t g_seq_age_ms;
extern uint32_t g_seq_sample;
extern float g_seq_pressure;
extern float g_seq_danger_average;
extern uint8_t g_seq_average_count;
extern float g_seq_score;
extern float g_seq_max_slack;
extern float g_seq_effective[4];
extern float g_seq_margin[4];
extern int8_t g_seq_side;
extern uint8_t g_seq_side_votes;
extern uint8_t g_seq_route_phase;
extern uint8_t g_seq_clear_votes;
extern uint32_t g_seq_route_replans;
extern float g_seq_waypoint_x;
extern float g_seq_waypoint_y;
extern float g_seq_waypoint_z;
extern float g_seq_path_offset_x;
extern float g_seq_path_offset_y;
extern float g_seq_return_delay_s;
extern float g_seq_scan_average;
extern uint8_t g_seq_scan_count;
extern uint32_t g_seq_scan_retries;
extern float g_seq_scan_target_yaw_deg;
extern float g_seq_scan_goal_yaw_deg;
extern float g_seq_scan_settle_s;
extern int8_t g_seq_scan_decision;
extern uint8_t g_seq_scan_pid_yaw_override;
extern uint8_t g_seq_barrier_active;
extern float g_seq_barrier_a0;
extern float g_seq_barrier_a1;
extern float g_seq_barrier_b;
extern float g_seq_forward_clearance_m;
extern float g_seq_cruise_speed_mps;
extern uint8_t g_seq_speed_halted;
extern float g_seq_goal_distance_m;
extern uint8_t g_seq_goal_reached;
extern float g_seq_forward_open_average[4];
extern float g_seq_scan_clearance_average[4];
extern float g_seq_side_score_0;
extern float g_seq_side_score_3;
extern float g_seq_scan_forward_slope;
extern float g_seq_scan_retry_delay_s;

PARAM_GROUP_START(seqAvoid)
PARAM_ADD(PARAM_UINT8, enable, &seqAvoidEnable)
PARAM_ADD(PARAM_UINT8, constrain, &seqAvoidConstraintEnable)
PARAM_ADD(PARAM_UINT8, logOnly, &seqAvoidLogOnly)
PARAM_ADD(PARAM_FLOAT, confMin, &seqAvoidConfidenceMin)
PARAM_ADD(PARAM_UINT32, maxAge, &seqAvoidMaxAgeMs)
PARAM_ADD(PARAM_UINT32, graceMs, &seqAvoidDropoutGraceMs)
PARAM_ADD(PARAM_FLOAT, droneRad, &seqAvoidDroneRadiusM)
PARAM_ADD(PARAM_FLOAT, trackMar, &seqAvoidTrackingMarginM)
PARAM_ADD(PARAM_FLOAT, latency, &seqAvoidLatencyS)
PARAM_ADD(PARAM_FLOAT, percMar, &seqAvoidPerceptionMarginM)
PARAM_ADD(PARAM_FLOAT, confGain, &seqAvoidConfidenceGainM)
PARAM_ADD(PARAM_FLOAT, defOff, &seqAvoidDefaultOffsetM)
PARAM_ADD(PARAM_FLOAT, maxRange, &seqAvoidMaxRangeM)
PARAM_ADD(PARAM_FLOAT, safeMin, &seqAvoidDirectionSafeMinM)
PARAM_ADD(PARAM_UINT8, avgN, &seqAvoidAverageWindow)
PARAM_ADD(PARAM_FLOAT, trigAvg, &seqAvoidTriggerAverage)
PARAM_ADD(PARAM_FLOAT, clearAvg, &seqAvoidClearAverage)
PARAM_ADD(PARAM_FLOAT, trigger, &seqAvoidTriggerM)
PARAM_ADD(PARAM_FLOAT, actEps, &seqAvoidActivationEpsM)
PARAM_ADD(PARAM_FLOAT, refShift, &seqAvoidReferenceShiftM)
PARAM_ADD(PARAM_FLOAT, returnDelay, &seqAvoidReturnDelayS)
PARAM_ADD(PARAM_FLOAT, returnRate, &seqAvoidReturnRateMps)
PARAM_ADD(PARAM_UINT8, scanEnable, &seqAvoidReturnScanEnable)
PARAM_ADD(PARAM_FLOAT, scanYaw, &seqAvoidReturnScanYawDeg)
PARAM_ADD(PARAM_FLOAT, scanYawRate, &seqAvoidReturnScanYawRateDegS)
PARAM_ADD(PARAM_FLOAT, scanSettle, &seqAvoidReturnScanSettleS)
PARAM_ADD(PARAM_UINT8, scanAvgN, &seqAvoidReturnScanWindow)
PARAM_ADD(PARAM_FLOAT, scanClear, &seqAvoidReturnScanClearAverage)
PARAM_ADD(PARAM_FLOAT, scanRetry, &seqAvoidReturnScanRetryS)
PARAM_ADD(PARAM_FLOAT, sideBias, &seqAvoidSideBiasM)
PARAM_ADD(PARAM_FLOAT, scanGrad, &seqAvoidScanGradientM)
PARAM_ADD(PARAM_FLOAT, scanImprove, &seqAvoidScanImprovementM)
PARAM_ADD(PARAM_FLOAT, scanRetryMin, &seqAvoidScanRetryMinS)
PARAM_ADD(PARAM_FLOAT, scanRetryMax, &seqAvoidScanRetryMaxS)
PARAM_ADD(PARAM_FLOAT, cruise, &seqAvoidCruiseSpeedMps)
PARAM_ADD(PARAM_FLOAT, cruiseAcc, &seqAvoidCruiseAccelMps2)
PARAM_ADD(PARAM_FLOAT, brakeAcc, &seqAvoidBrakingAccelMps2)
PARAM_ADD(PARAM_FLOAT, speedStop, &seqAvoidSpeedStopMinM)
PARAM_ADD(PARAM_FLOAT, speedResume, &seqAvoidSpeedResumeMinM)
PARAM_ADD(PARAM_FLOAT, goalTol, &seqAvoidGoalToleranceM)
PARAM_ADD(PARAM_FLOAT, sideMin, &seqAvoidSideMinimumM)
PARAM_ADD(PARAM_UINT8, sideVotes, &seqAvoidSideVotesRequired)
PARAM_ADD(PARAM_FLOAT, fwdMin, &seqAvoidForwardMinimumM)
PARAM_ADD(PARAM_FLOAT, fwdStep, &seqAvoidForwardStepM)
PARAM_ADD(PARAM_FLOAT, passDist, &seqAvoidPassDistanceM)
PARAM_ADD(PARAM_FLOAT, wpTol, &seqAvoidWaypointToleranceM)
PARAM_ADD(PARAM_UINT8, clearVotes, &seqAvoidClearVotesRequired)
PARAM_ADD(PARAM_FLOAT, maxLat, &seqAvoidMaxLateralM)
PARAM_ADD(PARAM_FLOAT, probeProg, &seqAvoidProbeProgressM)
PARAM_ADD(PARAM_UINT8, probeVotes, &seqAvoidProbeVotesRequired)
PARAM_ADD(PARAM_FLOAT, maxPriRes, &seqAvoidMaxPrimalResidual)
PARAM_ADD(PARAM_FLOAT, maxDuaRes, &seqAvoidMaxDualResidual)
PARAM_ADD(PARAM_UINT32, maxSolveUs, &seqAvoidMaxSolveUs)
PARAM_ADD(PARAM_FLOAT, slackPen, &seqAvoidSlackPenalty)
PARAM_ADD(PARAM_FLOAT, wDist, &seqAvoidDistanceWeight)
PARAM_ADD(PARAM_FLOAT, wGoal, &seqAvoidGoalWeight)
PARAM_ADD(PARAM_FLOAT, wHist, &seqAvoidHysteresisWeight)
PARAM_ADD(PARAM_FLOAT, wDyn, &seqAvoidDynamicWeight)
PARAM_ADD(PARAM_UINT8, kStart, &seqAvoidKStart)
PARAM_GROUP_STOP(seqAvoid)

LOG_GROUP_START(seqAvoid)
LOG_ADD(LOG_UINT8, valid, &g_seq_valid)
LOG_ADD(LOG_UINT8, stop, &g_seq_stop)
LOG_ADD(LOG_UINT8, mask, &g_seq_reliable_mask)
LOG_ADD(LOG_INT8, chosen, &g_seq_chosen)
LOG_ADD(LOG_UINT8, nCstr, &g_seq_constraints)
LOG_ADD(LOG_UINT8, grace, &g_seq_grace)
LOG_ADD(LOG_UINT32, graceAge, &g_seq_grace_age_ms)
LOG_ADD(LOG_UINT32, ageMs, &g_seq_age_ms)
LOG_ADD(LOG_UINT32, sample, &g_seq_sample)
LOG_ADD(LOG_FLOAT, pressure, &g_seq_pressure)
LOG_ADD(LOG_FLOAT, dangerAvg, &g_seq_danger_average)
LOG_ADD(LOG_UINT8, avgCount, &g_seq_average_count)
LOG_ADD(LOG_FLOAT, score, &g_seq_score)
LOG_ADD(LOG_FLOAT, maxSlack, &g_seq_max_slack)
LOG_ADD(LOG_FLOAT, eff0, &g_seq_effective[0])
LOG_ADD(LOG_FLOAT, eff1, &g_seq_effective[1])
LOG_ADD(LOG_FLOAT, eff2, &g_seq_effective[2])
LOG_ADD(LOG_FLOAT, eff3, &g_seq_effective[3])
LOG_ADD(LOG_FLOAT, mar0, &g_seq_margin[0])
LOG_ADD(LOG_FLOAT, mar1, &g_seq_margin[1])
LOG_ADD(LOG_FLOAT, mar2, &g_seq_margin[2])
LOG_ADD(LOG_FLOAT, mar3, &g_seq_margin[3])
LOG_ADD(LOG_INT8, side, &g_seq_side)
LOG_ADD(LOG_UINT8, sideVotes, &g_seq_side_votes)
LOG_ADD(LOG_UINT8, routePhase, &g_seq_route_phase)
LOG_ADD(LOG_UINT8, clearVotes, &g_seq_clear_votes)
LOG_ADD(LOG_UINT32, replans, &g_seq_route_replans)
LOG_ADD(LOG_FLOAT, waypointX, &g_seq_waypoint_x)
LOG_ADD(LOG_FLOAT, waypointY, &g_seq_waypoint_y)
LOG_ADD(LOG_FLOAT, waypointZ, &g_seq_waypoint_z)
LOG_ADD(LOG_FLOAT, pathOffX, &g_seq_path_offset_x)
LOG_ADD(LOG_FLOAT, pathOffY, &g_seq_path_offset_y)
LOG_ADD(LOG_FLOAT, returnWait, &g_seq_return_delay_s)
LOG_ADD(LOG_FLOAT, scanAvg, &g_seq_scan_average)
LOG_ADD(LOG_UINT8, scanCount, &g_seq_scan_count)
LOG_ADD(LOG_UINT32, scanRetries, &g_seq_scan_retries)
LOG_ADD(LOG_FLOAT, scanYaw, &g_seq_scan_target_yaw_deg)
LOG_ADD(LOG_FLOAT, scanYawGoal, &g_seq_scan_goal_yaw_deg)
LOG_ADD(LOG_FLOAT, scanSettle, &g_seq_scan_settle_s)
LOG_ADD(LOG_INT8, scanDecision, &g_seq_scan_decision)
LOG_ADD(LOG_UINT8, scanPidYaw, &g_seq_scan_pid_yaw_override)
LOG_ADD(LOG_UINT8, barrier, &g_seq_barrier_active)
LOG_ADD(LOG_FLOAT, barrierA0, &g_seq_barrier_a0)
LOG_ADD(LOG_FLOAT, barrierA1, &g_seq_barrier_a1)
LOG_ADD(LOG_FLOAT, barrierB, &g_seq_barrier_b)
LOG_ADD(LOG_FLOAT, fwdClear, &g_seq_forward_clearance_m)
LOG_ADD(LOG_FLOAT, speedCmd, &g_seq_cruise_speed_mps)
LOG_ADD(LOG_UINT8, speedHalt, &g_seq_speed_halted)
LOG_ADD(LOG_FLOAT, goalDist, &g_seq_goal_distance_m)
LOG_ADD(LOG_UINT8, goalReached, &g_seq_goal_reached)
LOG_ADD(LOG_FLOAT, openAvg0, &g_seq_forward_open_average[0])
LOG_ADD(LOG_FLOAT, openAvg1, &g_seq_forward_open_average[1])
LOG_ADD(LOG_FLOAT, openAvg2, &g_seq_forward_open_average[2])
LOG_ADD(LOG_FLOAT, openAvg3, &g_seq_forward_open_average[3])
LOG_ADD(LOG_FLOAT, scanClr0, &g_seq_scan_clearance_average[0])
LOG_ADD(LOG_FLOAT, scanClr1, &g_seq_scan_clearance_average[1])
LOG_ADD(LOG_FLOAT, scanClr2, &g_seq_scan_clearance_average[2])
LOG_ADD(LOG_FLOAT, scanClr3, &g_seq_scan_clearance_average[3])
LOG_ADD(LOG_FLOAT, sideScore0, &g_seq_side_score_0)
LOG_ADD(LOG_FLOAT, sideScore3, &g_seq_side_score_3)
LOG_ADD(LOG_FLOAT, scanSlope, &g_seq_scan_forward_slope)
LOG_ADD(LOG_FLOAT, scanRetryWait, &g_seq_scan_retry_delay_s)
LOG_GROUP_STOP(seqAvoid)
