#include "tinyracer_debug.h"
#include "log.h"
#include "param.h"

#if !defined(CONFIG_PLATFORM_SITL)
volatile MpcRetainedTrace mpc_retained __attribute__((section(".nzds")));
PARAM_GROUP_START(mpcTrace)
PARAM_ADD(PARAM_UINT32 | PARAM_RONLY, magic, &mpc_retained.magic)
PARAM_ADD(PARAM_UINT32 | PARAM_RONLY, stage, &mpc_retained.stage)
PARAM_ADD(PARAM_UINT32 | PARAM_RONLY, phase, &mpc_retained.phase)
PARAM_ADD(PARAM_UINT32 | PARAM_RONLY, cycle, &mpc_retained.cycle)
PARAM_ADD(PARAM_UINT32 | PARAM_RONLY, tick, &mpc_retained.tick)
PARAM_GROUP_STOP(mpcTrace)
#endif

TinyRacerDebugTelemetry tinyRacerDebug;

#if TINYMPC_LINE_BRAKE_TEST
uint8_t line_test_run = 0u;
PARAM_GROUP_START(lineTest)
PARAM_ADD(PARAM_UINT8, run, &line_test_run)
PARAM_GROUP_STOP(lineTest)
LOG_GROUP_START(lineTest)
LOG_ADD(LOG_UINT8, phase, &tinyRacerDebug.line_phase)
LOG_ADD(LOG_UINT8, reason, &tinyRacerDebug.line_reason)
LOG_ADD(LOG_UINT8, settled, &tinyRacerDebug.line_settled)
LOG_ADD(LOG_FLOAT, distance, &tinyRacerDebug.line_distance)
LOG_ADD(LOG_FLOAT, speed, &tinyRacerDebug.line_speed)
LOG_ADD(LOG_FLOAT, refS, &tinyRacerDebug.line_ref_s)
LOG_ADD(LOG_FLOAT, refV, &tinyRacerDebug.line_ref_v)
LOG_ADD(LOG_FLOAT, stopS, &tinyRacerDebug.line_stop_s)
LOG_GROUP_STOP(lineTest)
LOG_GROUP_START(lineModel)
LOG_ADD(LOG_UINT16, solver, &tinyRacerDebug.line_model_id)
LOG_ADD(LOG_UINT16, feedback, &tinyRacerDebug.line_feedback_model)
LOG_ADD(LOG_UINT8, valid, &tinyRacerDebug.line_model_valid)
LOG_ADD(LOG_UINT8, local, &tinyRacerDebug.line_feedback_local)
LOG_ADD(LOG_UINT8, solverLocal, &tinyRacerDebug.line_solver_local)
LOG_ADD(LOG_FLOAT, pitch, &tinyRacerDebug.line_pitch_deg)
LOG_ADD(LOG_FLOAT, rates, &tinyRacerDebug.line_body_rate)
LOG_GROUP_STOP(lineModel)
// Angles in degrees, body pitch rates in rad/s; nominal is time-aligned LQR
// target, ref is the worker's first MPC objective (not the LQR nominal).
LOG_GROUP_START(lineAtt)
LOG_ADD(LOG_FLOAT, roll, &tinyRacerDebug.line_att_roll)
LOG_ADD(LOG_FLOAT, pitch, &tinyRacerDebug.line_att_pitch)
LOG_ADD(LOG_FLOAT, q, &tinyRacerDebug.line_att_q)
LOG_ADD(LOG_FLOAT, refPitch, &tinyRacerDebug.line_att_ref_pitch)
LOG_ADD(LOG_FLOAT, refQ, &tinyRacerDebug.line_att_ref_q)
LOG_ADD(LOG_FLOAT, nomPitch, &tinyRacerDebug.line_att_nom_pitch)
LOG_ADD(LOG_FLOAT, nomQ, &tinyRacerDebug.line_att_nom_q)
LOG_ADD(LOG_FLOAT, nomQmax, &tinyRacerDebug.line_nominal_q_max)
LOG_ADD(LOG_UINT8, valid, &tinyRacerDebug.line_att_valid)
LOG_ADD(LOG_UINT8, damping, &tinyRacerDebug.line_recovery_damping)
LOG_GROUP_STOP(lineAtt)
// Thrust before/after the final LQR clamp in N, not measured motor thrust.
// Bit 0..3 in masks identifies motor 1..4; high and low are separate.
LOG_GROUP_START(lineMotor)
LOG_ADD(LOG_FLOAT, tauRaw, &tinyRacerDebug.line_pitch_torque_raw)
LOG_ADD(LOG_FLOAT, tauApplied, &tinyRacerDebug.line_pitch_torque_applied)
LOG_ADD(LOG_UINT8, pitchLimit, &tinyRacerDebug.line_pitch_limited)
LOG_ADD(LOG_FLOAT, raw1, &tinyRacerDebug.line_motor_raw_n[0])
LOG_ADD(LOG_FLOAT, raw2, &tinyRacerDebug.line_motor_raw_n[1])
LOG_ADD(LOG_FLOAT, raw3, &tinyRacerDebug.line_motor_raw_n[2])
LOG_ADD(LOG_FLOAT, raw4, &tinyRacerDebug.line_motor_raw_n[3])
LOG_ADD(LOG_FLOAT, clip1, &tinyRacerDebug.line_motor_clip_n[0])
LOG_ADD(LOG_FLOAT, clip2, &tinyRacerDebug.line_motor_clip_n[1])
LOG_ADD(LOG_FLOAT, clip3, &tinyRacerDebug.line_motor_clip_n[2])
LOG_ADD(LOG_FLOAT, clip4, &tinyRacerDebug.line_motor_clip_n[3])
LOG_ADD(LOG_UINT8, high, &tinyRacerDebug.line_motor_high)
LOG_ADD(LOG_UINT8, low, &tinyRacerDebug.line_motor_low)
LOG_GROUP_STOP(lineMotor)
#endif

#if TINYMPC_HOVER_ONLY && !TINYMPC_RATE_CASCADE && !defined(TINYMPC_DIRECT_PLAN_REPLAY) && (!defined(CONFIG_PLATFORM_SITL) || defined(TINYMPC_SITL_LQR_EQUIVALENCE))
uint8_t mpc_bench_run = 0u;
PARAM_GROUP_START(mpcBench)
PARAM_ADD(PARAM_UINT8, run, &mpc_bench_run)
PARAM_GROUP_STOP(mpcBench)
#endif

LOG_GROUP_START(trRef)
LOG_ADD(LOG_FLOAT, x, &tinyRacerDebug.ref_x)
LOG_ADD(LOG_FLOAT, y, &tinyRacerDebug.ref_y)
LOG_ADD(LOG_FLOAT, z, &tinyRacerDebug.ref_z)
LOG_ADD(LOG_FLOAT, hx, &tinyRacerDebug.horizon_x)
LOG_ADD(LOG_FLOAT, hy, &tinyRacerDebug.horizon_y)
LOG_ADD(LOG_FLOAT, hz, &tinyRacerDebug.horizon_z)
LOG_GROUP_STOP(trRef)

LOG_GROUP_START(trCyl)
LOG_ADD(LOG_FLOAT, x, &tinyRacerDebug.cylinder_x)
LOG_ADD(LOG_FLOAT, y, &tinyRacerDebug.cylinder_y)
LOG_ADD(LOG_FLOAT, r, &tinyRacerDebug.cylinder_radius)
LOG_ADD(LOG_FLOAT, nx, &tinyRacerDebug.plane_nx)
LOG_ADD(LOG_FLOAT, ny, &tinyRacerDebug.plane_ny)
LOG_ADD(LOG_FLOAT, b, &tinyRacerDebug.plane_boundary)
LOG_GROUP_STOP(trCyl)

LOG_GROUP_START(trCtl)
LOG_ADD(LOG_UINT8, catch, &tinyRacerDebug.line_catch)
LOG_ADD(LOG_UINT8, visFresh, &tinyRacerDebug.line_vision_fresh)
LOG_ADD(LOG_UINT8, visStop, &tinyRacerDebug.line_vision_stop)
LOG_ADD(LOG_UINT8, pidFallback, &tinyRacerDebug.pid_fallback)
LOG_ADD(LOG_UINT8, direct, &tinyRacerDebug.direct_active)
LOG_ADD(LOG_UINT8, guard, &tinyRacerDebug.fallback_guard)
LOG_ADD(LOG_UINT8, fbReason, &tinyRacerDebug.fallback_reason)
LOG_ADD(LOG_UINT32, planAge, &tinyRacerDebug.plan_age_ms)
LOG_ADD(LOG_UINT32, fbAgeMs, &tinyRacerDebug.fallback_age_ms)
LOG_ADD(LOG_UINT32, directMs, &tinyRacerDebug.direct_duration_ms)
LOG_ADD(LOG_UINT32, queueUs, &tinyRacerDebug.snapshot_queue_us)
LOG_ADD(LOG_UINT32, prepUs, &tinyRacerDebug.preparation_us)
LOG_ADD(LOG_UINT32, pubAgeUs, &tinyRacerDebug.publish_age_us)
LOG_ADD(LOG_UINT32, readyAge, &tinyRacerDebug.ready_plan_age_ms)
LOG_ADD(LOG_UINT32, heldMax, &tinyRacerDebug.held_plan_max_ms)
#if TINYMPC_LQR_FEEDBACK
LOG_ADD(LOG_UINT32, lqrUs, &tinyRacerDebug.lqr_us)
LOG_ADD(LOG_UINT32, lqrCycles, &tinyRacerDebug.lqr_cycles)
LOG_ADD(LOG_UINT32, lqrGapMax, &tinyRacerDebug.lqr_gap_max_ms)
LOG_ADD(LOG_UINT8, lqrSat, &tinyRacerDebug.lqr_saturation)
LOG_ADD(LOG_UINT8, lqrValid, &tinyRacerDebug.lqr_valid)
LOG_ADD(LOG_FLOAT, xGap, &tinyRacerDebug.admm_state_gap)
LOG_ADD(LOG_FLOAT, uGapN, &tinyRacerDebug.admm_input_gap_n)
#endif
LOG_ADD(LOG_FLOAT, lateral, &tinyRacerDebug.lateral_offset)
LOG_ADD(LOG_FLOAT, violation, &tinyRacerDebug.plane_violation)
LOG_ADD(LOG_FLOAT, consensus, &tinyRacerDebug.consensus_error)
LOG_ADD(LOG_FLOAT, slack, &tinyRacerDebug.slack)
LOG_ADD(LOG_UINT32, solveUs, &tinyRacerDebug.solve_us)
LOG_ADD(LOG_UINT32, workerUs, &tinyRacerDebug.worker_us)
LOG_ADD(LOG_UINT32, stackFree, &tinyRacerDebug.worker_stack_words)
LOG_ADD(LOG_UINT32, cycles, &tinyRacerDebug.worker_cycles)
LOG_ADD(LOG_UINT32, overruns, &tinyRacerDebug.worker_overruns)
LOG_ADD(LOG_UINT8, mode, &tinyRacerDebug.mode)
LOG_ADD(LOG_UINT8, cyl, &tinyRacerDebug.cylinder_active)
LOG_ADD(LOG_INT8, side, &tinyRacerDebug.pass_side)
LOG_GROUP_STOP(trCtl)

LOG_GROUP_START(lineTime)
LOG_ADD(LOG_UINT32, samples, &tinyRacerDebug.line_timing.samples)
LOG_ADD(LOG_UINT32, firstPrep, &tinyRacerDebug.line_timing.first_prep)
LOG_ADD(LOG_UINT32, firstSolve, &tinyRacerDebug.line_timing.first_solve)
LOG_ADD(LOG_UINT32, firstPub, &tinyRacerDebug.line_timing.first_publish)
LOG_ADD(LOG_UINT32, firstWork, &tinyRacerDebug.line_timing.first_worker)
LOG_ADD(LOG_UINT32, maxPrep, &tinyRacerDebug.line_timing.max_prep)
LOG_ADD(LOG_UINT32, maxSolve, &tinyRacerDebug.line_timing.max_solve)
LOG_ADD(LOG_UINT32, maxPub, &tinyRacerDebug.line_timing.max_publish)
LOG_ADD(LOG_UINT32, maxWork, &tinyRacerDebug.line_timing.max_worker)
LOG_GROUP_STOP(lineTime)

/* Output readback is a command-based steady-thrust prediction, not measured
 * rotor thrust. qdot is a finite difference; delays/contact affect comparison. */
LOG_GROUP_START(lineTorque)
LOG_ADD(LOG_FLOAT, qdot, &tinyRacerDebug.line_qdot)
LOG_ADD(LOG_FLOAT, alphaCmd, &tinyRacerDebug.line_alpha_cmd)
LOG_ADD(LOG_FLOAT, alphaOut, &tinyRacerDebug.line_alpha_out)
LOG_ADD(LOG_FLOAT, tauOut, &tinyRacerDebug.line_tau_out)
LOG_ADD(LOG_FLOAT, outGapN, &tinyRacerDebug.line_output_gap_n)
LOG_ADD(LOG_UINT32, dtMs, &tinyRacerDebug.line_qdot_dt_ms)
LOG_GROUP_STOP(lineTorque)

/* MPC physical setpoints: collective N and body rates rad/s. Values are held
 * when inactive; active/pidFallback determine whether they have authority. */
LOG_GROUP_START(mpcPid)
LOG_ADD(LOG_UINT8, altPid, &tinyRacerDebug.altitude_pid_active)
LOG_ADD(LOG_FLOAT, zHold, &tinyRacerDebug.altitude_target_z)
LOG_ADD(LOG_FLOAT, thrustCmd, &tinyRacerDebug.altitude_thrust)
LOG_ADD(LOG_UINT8, mode, &tinyRacerDebug.maneuver_mode)
LOG_ADD(LOG_UINT32, caps, &tinyRacerDebug.maneuver_caps)
LOG_ADD(LOG_UINT8, active, &tinyRacerDebug.rate_active)
LOG_ADD(LOG_FLOAT, thrustN, &tinyRacerDebug.rate_collective)
LOG_ADD(LOG_FLOAT, p, &tinyRacerDebug.rate_p)
LOG_ADD(LOG_FLOAT, q, &tinyRacerDebug.rate_q)
LOG_ADD(LOG_FLOAT, r, &tinyRacerDebug.rate_r)
LOG_ADD(LOG_UINT32, ageMs, &tinyRacerDebug.rate_plan_age_ms)
LOG_GROUP_STOP(mpcPid)

LOG_GROUP_START(trOpen)
LOG_ADD(LOG_FLOAT, probability, &tinyRacerDebug.square_opening_probability)
LOG_ADD(LOG_UINT8, eligible, &tinyRacerDebug.square_opening_eligible)
LOG_ADD(LOG_UINT8, seen, &tinyRacerDebug.square_opening_seen)
LOG_GROUP_STOP(trOpen)

LOG_GROUP_START(olgmd)
LOG_ADD(LOG_UINT8, fresh, &tinyRacerDebug.olgmd_fresh)
LOG_ADD(LOG_UINT8, detect, &tinyRacerDebug.olgmd_detected)
LOG_ADD(LOG_UINT8, eligible, &tinyRacerDebug.olgmd_trigger_eligible)
LOG_ADD(LOG_UINT8, brake, &tinyRacerDebug.olgmd_brake_latched)
LOG_ADD(LOG_UINT8, termStop, &tinyRacerDebug.olgmd_terminal_stop)
LOG_ADD(LOG_UINT8, phase, &tinyRacerDebug.olgmd_phase)
LOG_ADD(LOG_UINT32, trig, &tinyRacerDebug.olgmd_trigger_count)
LOG_ADD(LOG_UINT32, posTrig, &tinyRacerDebug.olgmd_positive_trigger_count)
LOG_ADD(LOG_UINT32, staleTrig, &tinyRacerDebug.olgmd_stale_trigger_count)
LOG_ADD(LOG_UINT32, release, &tinyRacerDebug.olgmd_release_count)
LOG_GROUP_STOP(olgmd)
