#!/usr/bin/env python3
"""Regenerate fixed-rho cache from checked-in A/B/Q/R for state+input ADMM."""
from pathlib import Path
import re
import numpy as np
from scipy.linalg import solve_discrete_are
import argparse
p=argparse.ArgumentParser();p.add_argument("--position-weight",type=float,default=100);p.add_argument("--output",type=Path,required=True);args=p.parse_args()
base=Path(__file__).resolve().parents[1]/'src'
s=(base/'tinympc_generated_params.h').read_text()
def arr(name,shape):
 body=re.search(r'tinympc_generated_'+name+r'\[\d+\] = \{(.*?)\};',s,re.S)[1]
 return np.array([float(v.strip().rstrip('f')) for v in body.split(',') if v.strip()]).reshape(shape)
A=arr('A',(12,12)); B=arr('B',(12,4)); f=arr('f',(12,)); Q=np.diag(arr('Q_diagonal',(12,))); R=np.diag(arr('R_diagonal',(4,)))
rho=25000.; weights=np.ones(12); weights[3:5]=10000.; weights[9:12]=100.
weights[:2]=args.position_weight
assert args.position_weight>0
Qa=Q+rho*np.diag(weights); Ra=R+rho*np.eye(4)
P=solve_discrete_are(A,B,Qa,Ra); inv=np.linalg.inv(Ra+B.T@P@B); K=inv@B.T@P@A; C=(A-B@K).T
assert np.linalg.norm(P-Qa-A.T@P@A+A.T@P@B@K) / np.linalg.norm(P) < 1e-8
assert np.linalg.norm(K.T@Ra-C@P@B) / max(1., np.linalg.norm(K.T@Ra)) < 1e-6
parts=[f'// Generated by tools/generate_depthgate_constraint_cache.py; rho={rho:g}.\n#pragma once\nstatic const float depthgate_cache_rho = {rho:.1f}f;\n']
for name,v in [('state_weights',weights),('Pinf',P),('Kinf',K),('Quu_inv',inv),('AmBKt',C),('coeff_d2p',np.zeros((12,4))),('APf',C@P@f),('BPf',B.T@P@f)]:
 def number(x):
  t=format(float(x),'.9g');return t+('.0' if '.' not in t and 'e' not in t else '')+'f'
 parts.append('static const float depthgate_cache_'+name+'['+str(v.size)+'] = {\n'+',\n'.join(', '.join(number(x) for x in v.flatten()[i:i+6]) for i in range(0,v.size,6))+'\n};\n')
args.output.write_text('\n'.join(parts))
print('DARE and cache identities verified')
