#!/usr/bin/env python3
"""Generate offline TinyMPC bundles for signed coordinated turns."""

from __future__ import annotations

import math
from pathlib import Path

import autograd as ag
import autograd.numpy as anp
import numpy as np

import tinympc_to_crazyflie_adapter as base


BANK_ANGLES_DEG = (15.0, 30.0, 60.0)
SPEED_BY_BANK_DEG = {15.0: 1.0, 30.0: 2.0, 60.0: 5.0}


def rotation_x(angle: float) -> np.ndarray:
    c, s = math.cos(angle), math.sin(angle)
    return np.asarray([[1, 0, 0], [0, c, -s], [0, s, c]], float)


def allocation(problem: base.CompileTimeProblem) -> np.ndarray:
    arm = 0.03535
    yaw_ratio = 7.73e-11 / 3.72e-8
    return np.asarray([
        [1, 1, 1, 1],
        [-arm, -arm, arm, arm],
        [-arm, arm, arm, -arm],
        [-yaw_ratio, yaw_ratio, -yaw_ratio, yaw_ratio],
    ], float)


def bundle(problem: base.CompileTimeProblem, direction: int, bank_deg: float, speed_mps: float):
    # direction +1 is a left turn. With body +Y left and the generator's
    # quaternion convention, a left coordinated turn has negative roll.
    roll = -direction * math.radians(bank_deg)
    yaw_rate = direction * 9.81 * math.tan(math.radians(bank_deg)) / speed_mps
    rotation = rotation_x(roll)
    omega_body = rotation.T @ np.asarray([0.0, 0.0, yaw_rate])
    xbar = np.zeros(problem.state_dim)
    xbar[3] = math.tan(roll / 2.0)
    xbar[6] = speed_mps
    xbar[9:12] = omega_body

    inertia = np.diag([2.3951e-5, 2.3951e-5, 3.2347e-5])
    torque = np.cross(omega_body, inertia @ omega_body)
    total_thrust = base.vehicle_mass(problem) * 9.81 / math.cos(roll)
    physical_ubar = np.linalg.solve(
        allocation(problem), np.r_[total_thrust, torque]
    )
    _, _, hover = base.build_input_bounds_and_reference(problem)
    delta_ubar = physical_ubar - hover

    dynamics = base.build_continuous_model(problem)
    discrete = lambda x, du: base.rk4(dynamics, x, hover + du, problem.model_dt_s)
    xnext = np.asarray(discrete(anp.asarray(xbar), anp.asarray(delta_ubar)), float)
    A = np.asarray(ag.jacobian(lambda x: discrete(x, anp.asarray(delta_ubar)))(anp.asarray(xbar)), float)
    B = np.asarray(ag.jacobian(lambda du: discrete(anp.asarray(xbar), du))(anp.asarray(delta_ubar)), float)
    affine = xnext - A @ xbar - B @ delta_ubar
    Q, R = base.build_cost_matrices(problem)
    cache = base.build_upstream_cache(problem, A, B, affine, Q, R)
    coeff_d2p = cache["Kinf"].T @ R - cache["AmBKt"] @ cache["Pinf"] @ B
    cache = dict(cache, coeff_d2p=coeff_d2p)
    return A, B, affine, xbar, delta_ubar, physical_ubar, cache


def render() -> str:
    problem = base.PROBLEM
    sections = []
    for bank_deg in BANK_ANGLES_DEG:
        angle_name = f"{bank_deg:g}"
        speed_mps = SPEED_BY_BANK_DEG[bank_deg]
        for side, direction in (("left", 1), ("right", -1)):
            A, B, affine, xbar, delta_ubar, physical_ubar, cache = bundle(problem, direction, bank_deg, speed_mps)
            prefix = f"tinympc_bank_{side}_{angle_name}"
            arrays = [
                base.format_c_array(f"{prefix}_A", A),
                base.format_c_array(f"{prefix}_B", B),
                base.format_c_array(f"{prefix}_f", affine),
                base.format_c_array(f"{prefix}_nominal_state", xbar),
                base.format_c_array(f"{prefix}_nominal_input", delta_ubar),
                base.format_c_array(f"{prefix}_physical_input", physical_ubar),
            ]
            arrays.extend(base.format_c_array(f"{prefix}_{key}", value) for key, value in cache.items())
            sections.append("\n\n".join(arrays))
    return f"""/* Autogenerated by generate_banked_model_bank.py. */
#ifndef TINYMPC_BANKED_MODEL_BANK_H
#define TINYMPC_BANKED_MODEL_BANK_H

#define TINYMPC_BANK_MODEL_15_SPEED_MPS (1.0f)
#define TINYMPC_BANK_MODEL_30_SPEED_MPS (2.0f)
#define TINYMPC_BANK_MODEL_60_SPEED_MPS (5.0f)

{chr(10).join(sections)}

#endif
"""


def main() -> int:
    output = Path(__file__).resolve().parents[2] / "src" / "tinympc_banked_model_bank.h"
    output.write_text(render())
    print(f"wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
