#!/usr/bin/env python3
"""Generate compact firmware references used by canonical racing courses.

Long course references use the ordinary 13-state level-flight path.
"""

from __future__ import annotations

import csv
from dataclasses import dataclass
import math
import numpy as np
from pathlib import Path


APP_ROOT = Path(__file__).resolve().parents[2]
DT_S = 0.02


@dataclass(frozen=True)
class Track:
    source: str
    name: str
    tangent_heading: int
    turn_direction: int
    time_scale: float = 1.0
    obstacle_approach_start_index: int | None = None
    obstacle_index: int | None = None
    obstacle_approach_end_index: int | None = None


TRACKS = (
    Track("chicane.csv", "chicane", 1, 0),
    Track("hairpin_180.csv", "hairpin_180", 1, 1),
)

CANONICAL_TRACKS = (
    Track("chicane.csv", "canonical_chicane", 1, 0, 2.5, 356, 421, 446),
    Track("hairpin_180.csv", "canonical_hairpin", 1, 1, 4.0),
)


def literal(value: float) -> str:
    value = 0.0 if abs(value) < 5.0e-9 else value
    result = f"{value:.8g}"
    if "." not in result and "e" not in result:
        result += ".0"
    return result + "f"


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    if len(rows) < 2:
        raise ValueError(f"{path} has no usable trajectory")
    return rows


def ordered(row: dict[str, str], include_motors: bool) -> list[float]:
    fields = [
        "x", "y", "z", "qw", "qx", "qy", "qz",
        "vx", "vy", "vz", "wx", "wy", "wz",
    ]
    if include_motors:
        fields.extend(f"motor_{index}_thrust_n" for index in range(4))
    return [float(row[field]) for field in fields]


def render_track(track: Track, output: Path) -> None:
    rows = read_rows(APP_ROOT / "sim/trajectories/racing" / track.source)
    guard = f"TRAJ_{track.name.upper()}_50HZ_H"
    data = [ordered(row, False) for row in rows]
    output.write_text("\n".join([
        "/* Autogenerated by generate_canonical_course_artifacts.py. */",
        f"#ifndef {guard}", f"#define {guard}", "",
        f'#define TRAJECTORY_NAME "{track.name}"',
        "#define TRAJECTORY_SAMPLE_RATE_HZ 50",
        f"#define TRAJECTORY_SAMPLE_DT_S ({literal(DT_S)})",
        f"#define TRAJECTORY_DURATION_S ({literal(float(rows[-1]['t']))})",
        f"#define TRAJECTORY_SAMPLE_COUNT {len(rows)}",
        "#define TRAJECTORY_REFERENCE_DIM 13",
        "#define TRAJECTORY_LOOPS 0",
        f"#define TRAJECTORY_TANGENT_HEADING {track.tangent_heading}",
        f"#define TRAJECTORY_TURN_DIRECTION {track.turn_direction}",
        "",
        "// [p_W(3), q_WB(wxyz), v_W(3), omega_B(3)]",
        "static const float trajectory_reference_data"
        "[TRAJECTORY_SAMPLE_COUNT][TRAJECTORY_REFERENCE_DIM] = {",
        *[
            "  {" + ", ".join(literal(value) for value in sample) + "},"
            for sample in data
        ],
        "};", "", f"#endif  // {guard}", "",
    ]))


def yaw_from_row(row: dict[str, str]) -> float:
    qw, qx, qy, qz = (float(row[key]) for key in ("qw", "qx", "qy", "qz"))
    return math.atan2(2.0 * (qw * qz + qx * qy),
                      1.0 - 2.0 * (qy * qy + qz * qz))


def render_slow_track(track: Track, output: Path) -> None:
    rows = read_rows(APP_ROOT / "sim/trajectories/racing" / track.source)
    source_t = np.asarray([float(row["t"]) for row in rows])
    duration = float(source_t[-1]) * track.time_scale
    target_t = np.arange(0.0, duration + 0.5 * DT_S, DT_S)
    query_t = target_t / track.time_scale
    x = np.interp(query_t, source_t, [float(row["x"]) for row in rows])
    y = np.interp(query_t, source_t, [float(row["y"]) for row in rows])
    z = np.interp(query_t, source_t, [float(row["z"]) for row in rows])
    vx = np.gradient(x, DT_S)
    vy = np.gradient(y, DT_S)
    yaw_source = np.unwrap([yaw_from_row(row) for row in rows])
    yaw = np.interp(query_t, source_t, yaw_source)
    yaw_rate = np.gradient(yaw, DT_S)
    samples = []
    for index in range(len(target_t)):
        samples.append([
            x[index], y[index], z[index], math.cos(0.5 * yaw[index]),
            0.0, 0.0, math.sin(0.5 * yaw[index]),
            vx[index], vy[index], 0.0, 0.0, 0.0, yaw_rate[index],
        ])
    rendered_track = track
    if track.name == "canonical_hairpin":
        cumulative = np.concatenate(([0.0], np.cumsum(np.hypot(
            np.diff(x), np.diff(y)))))
        obstacle_center = np.asarray([2.24, 0.718])
        nearest = int(np.argmin(np.hypot(
            x - obstacle_center[0], y - obstacle_center[1])))
        approach_start = int(np.argmin(np.abs(
            cumulative - max(0.0, cumulative[nearest] - 1.5))))
        approach_end = int(np.argmin(np.abs(
            cumulative - min(cumulative[-1], cumulative[nearest] + 0.5))))
        rendered_track = Track(
            track.source, track.name, track.tangent_heading,
            track.turn_direction, track.time_scale,
            approach_start, nearest, approach_end)
    render_samples(rendered_track, samples, duration, output)


def render_samples(track: Track, samples: list[list[float]], duration: float,
                   output: Path) -> None:
    guard = f"TRAJ_{track.name.upper()}_50HZ_H"
    output.write_text("\n".join([
        "/* Autogenerated by generate_canonical_course_artifacts.py. */",
        f"#ifndef {guard}", f"#define {guard}", "",
        f'#define TRAJECTORY_NAME "{track.name}"',
        "#define TRAJECTORY_SAMPLE_RATE_HZ 50",
        f"#define TRAJECTORY_SAMPLE_DT_S ({literal(DT_S)})",
        f"#define TRAJECTORY_DURATION_S ({literal(duration)})",
        f"#define TRAJECTORY_SAMPLE_COUNT {len(samples)}",
        "#define TRAJECTORY_REFERENCE_DIM 13", "#define TRAJECTORY_LOOPS 0",
        f"#define TRAJECTORY_TANGENT_HEADING {track.tangent_heading}",
        f"#define TRAJECTORY_TURN_DIRECTION {track.turn_direction}",
        *(
            [
                "#define TRAJECTORY_OBSTACLE_APPROACH_WINDOW 1",
                "#define TRAJECTORY_OBSTACLE_APPROACH_START_INDEX "
                f"{track.obstacle_approach_start_index}U",
                "#define TRAJECTORY_OBSTACLE_INDEX "
                f"{track.obstacle_index}U",
                "#define TRAJECTORY_OBSTACLE_APPROACH_END_INDEX "
                f"{track.obstacle_approach_end_index}U",
            ]
            if track.obstacle_approach_start_index is not None
            else []
        ),
        "",
        "// [p_W(3), q_WB(wxyz), v_W(3), omega_B(3)]",
        "static const float trajectory_reference_data"
        "[TRAJECTORY_SAMPLE_COUNT][TRAJECTORY_REFERENCE_DIM] = {",
        *["  {" + ", ".join(literal(value) for value in sample) + "},"
          for sample in samples],
        "};", "", f"#endif  // {guard}", "",
    ]))


def render_figure8_track(output: Path) -> None:
    duration = 72.0
    count = int(round(duration / DT_S)) + 1
    u = np.linspace(0.0, 1.0, count)
    ramp_fraction = 0.15
    progress = np.empty_like(u)
    ramp_area = 0.5 * ramp_fraction
    normalization = 1.0 - ramp_fraction
    first = u < ramp_fraction
    last = u > 1.0 - ramp_fraction
    middle = ~(first | last)
    progress[first] = (
        0.5 * u[first]
        - ramp_fraction / (2.0 * math.pi)
        * np.sin(math.pi * u[first] / ramp_fraction)
    ) / normalization
    progress[middle] = (
        ramp_area + u[middle] - ramp_fraction
    ) / normalization
    mirrored = 1.0 - u[last]
    progress[last] = 1.0 - (
        0.5 * mirrored
        - ramp_fraction / (2.0 * math.pi)
        * np.sin(math.pi * mirrored / ramp_fraction)
    ) / normalization
    theta = 2.0 * math.pi * progress
    raw_x = 0.5 * np.sin(theta)
    raw_y = np.sin(2.0 * theta)
    # Align the initial path tangent (0.5, 2.0) with launch +x. This lets the
    # stored yaw be relative to the handoff yaw, as it is for every other
    # tangent-heading racing trajectory.
    initial_tangent_yaw = math.atan2(2.0, 0.5)
    rotate_cos = math.cos(initial_tangent_yaw)
    rotate_sin = math.sin(initial_tangent_yaw)
    x = rotate_cos * raw_x + rotate_sin * raw_y
    y = -rotate_sin * raw_x + rotate_cos * raw_y
    vx, vy = np.gradient(x, DT_S), np.gradient(y, DT_S)
    yaw = np.unwrap(np.arctan2(vy, vx))
    yaw -= yaw[0]
    yaw_rate = np.gradient(yaw, DT_S)
    samples = [
        [x[i], y[i], 1.1, math.cos(0.5 * yaw[i]), 0.0, 0.0,
         math.sin(0.5 * yaw[i]), vx[i], vy[i], 0.0, 0.0, 0.0,
         yaw_rate[i]]
        for i in range(count)
    ]
    cumulative = np.concatenate(([0.0], np.cumsum(np.hypot(
        np.diff(x), np.diff(y)))))
    # Keep the obstacle on the nominal path, but place it before the lobe's
    # tight turnaround so the vision bypass is a realizable parallel lane.
    obstacle_center = np.asarray([0.2599, -0.4491])
    nearest = int(np.argmin(np.hypot(
        x - obstacle_center[0], y - obstacle_center[1])))
    approach_start = int(np.argmin(np.abs(
        cumulative - max(0.0, cumulative[nearest] - 1.0))))
    approach_end = int(np.argmin(np.abs(
        cumulative - min(cumulative[-1], cumulative[nearest] + 0.5))))
    render_samples(Track(
        "", "canonical_figure8", 1, 0, 1.0,
        approach_start, nearest, approach_end), samples,
                   duration, output)


def render_circle_track(output: Path) -> None:
    duration = 24.0
    radius = 0.75
    count = int(round(duration / DT_S)) + 1
    u = np.linspace(0.0, 1.0, count)
    progress = 10.0 * u**3 - 15.0 * u**4 + 6.0 * u**5
    theta = 2.0 * math.pi * progress
    x = radius * np.sin(theta)
    y = radius * (1.0 - np.cos(theta))
    vx, vy = np.gradient(x, DT_S), np.gradient(y, DT_S)
    yaw_rate = np.gradient(theta, DT_S)
    samples = [
        [x[i], y[i], 1.1, math.cos(0.5 * theta[i]), 0.0, 0.0,
         math.sin(0.5 * theta[i]), vx[i], vy[i], 0.0, 0.0, 0.0,
         yaw_rate[i]]
        for i in range(count)
    ]
    render_samples(Track("", "canonical_circle", 1, 1, 1.0, 508, 687, 761), samples,
                   duration, output)


def render_corridor_track(output: Path) -> None:
    duration = 18.0
    distance = 5.0
    count = int(round(duration / DT_S)) + 1
    samples = []
    pitches = []
    for index in range(count):
        u = index / (count - 1)
        s = 10.0 * u**3 - 15.0 * u**4 + 6.0 * u**5
        ds = 30.0 * u**2 - 60.0 * u**3 + 30.0 * u**4
        dds = 60.0 * u - 180.0 * u**2 + 120.0 * u**3
        x = distance * s
        vx = distance * ds / duration
        ax = distance * dds / (duration * duration)
        pitch = math.atan2(ax, 9.81)
        pitches.append(pitch)
        samples.append([x, 0.0, 1.1, math.cos(0.5 * pitch), 0.0,
                        math.sin(0.5 * pitch), 0.0, vx, 0.0, 0.0,
                        0.0, 0.0, 0.0])
    for index, sample in enumerate(samples):
        before = pitches[max(0, index - 1)]
        after = pitches[min(count - 1, index + 1)]
        denominator = DT_S * (2 if 0 < index < count - 1 else 1)
        sample[11] = (after - before) / denominator
    guard = "TRAJ_CANONICAL_CORRIDOR_50HZ_H"
    output.write_text("\n".join([
        "/* Autogenerated by generate_canonical_course_artifacts.py. */",
        f"#ifndef {guard}", f"#define {guard}", "",
        '#define TRAJECTORY_NAME "canonical_corridor"',
        "#define TRAJECTORY_SAMPLE_RATE_HZ 50",
        f"#define TRAJECTORY_SAMPLE_DT_S ({literal(DT_S)})",
        f"#define TRAJECTORY_DURATION_S ({literal(duration)})",
        f"#define TRAJECTORY_SAMPLE_COUNT {count}",
        "#define TRAJECTORY_REFERENCE_DIM 13",
        "#define TRAJECTORY_LOOPS 0",
        "#define TRAJECTORY_TANGENT_HEADING 0",
        "#define TRAJECTORY_TURN_DIRECTION 0",
        "#define TRAJECTORY_OBSTACLE_APPROACH_WINDOW 1",
        "#define TRAJECTORY_OBSTACLE_APPROACH_START_INDEX 222U",
        "#define TRAJECTORY_OBSTACLE_INDEX 382U",
        "#define TRAJECTORY_OBSTACLE_APPROACH_END_INDEX 431U", "",
        "// [p_W(3), q_WB(wxyz), v_W(3), omega_B(3)]",
        "static const float trajectory_reference_data"
        "[TRAJECTORY_SAMPLE_COUNT][TRAJECTORY_REFERENCE_DIM] = {",
        *["  {" + ", ".join(literal(value) for value in sample) + "},"
          for sample in samples],
        "};", "", f"#endif  // {guard}", "",
    ]))


def render_dronet_u_track(output: Path) -> None:
    """Render the published PULP-DroNet v3 U-course centerline.

    The paper fixes the 5.0 m by 4.7 m footprint, two 2.0 m straight
    corridors, and their 0.7 m separation, but does not publish a turn radius
    or centerline.  This reference follows the center of each straight and a
    smooth, diagram-matched turnaround that stays inside the measured
    footprint.  Geometry is sampled by arc length so progress speed remains a
    physical m/s command rather than depending on the drawing parameter.
    """
    straight_length = 3.45
    centerline_separation = 2.7
    turnaround_radius_x = 1.00
    sample_spacing_m = 0.02

    # Half ellipse: it is tangent to both straights, spans their published
    # 2.7 m centerline separation, and stays 0.55 m inside the outer wall. The
    # paper does not specify this centerline, so it remains a disclosed
    # approximation.
    turn_angle = np.linspace(-0.5 * math.pi, 0.5 * math.pi, 1601)
    turn = np.column_stack((
        straight_length + turnaround_radius_x * np.cos(turn_angle),
        0.5 * centerline_separation
        + 0.5 * centerline_separation * np.sin(turn_angle),
    ))
    dense = np.vstack((
        np.column_stack((np.linspace(0.0, straight_length, 1201),
                         np.zeros(1201))),
        turn[1:],
        np.column_stack((np.linspace(straight_length, 0.0, 1201)[1:],
                         np.full(1200, centerline_separation))),
    ))
    dense_s = np.concatenate(([0.0], np.cumsum(np.hypot(
        np.diff(dense[:, 0]), np.diff(dense[:, 1])))))
    route_s = np.arange(0.0, dense_s[-1], sample_spacing_m)
    route_s = np.append(route_s, dense_s[-1])
    x = np.interp(route_s, dense_s, dense[:, 0])
    y = np.interp(route_s, dense_s, dense[:, 1])
    dx = np.gradient(x, route_s, edge_order=2)
    dy = np.gradient(y, route_s, edge_order=2)
    tangent_norm = np.hypot(dx, dy)
    tx, ty = dx / tangent_norm, dy / tangent_norm
    yaw = np.unwrap(np.arctan2(ty, tx))
    curvature = np.gradient(yaw, route_s, edge_order=2)
    samples = [
        [x[i], y[i], 0.5, math.cos(0.5 * yaw[i]), 0.0, 0.0,
         math.sin(0.5 * yaw[i]), tx[i], ty[i], 0.0,
         0.0, 0.0, curvature[i]]
        for i in range(len(route_s))
    ]
    render_samples(Track("", "dronet_u", 1, 1), samples,
                   (len(samples) - 1) * DT_S, output)


def main() -> int:
    output = APP_ROOT / "src/trajectories/50hz"
    output.mkdir(parents=True, exist_ok=True)
    render_corridor_track(output / "traj_canonical_corridor_50hz.h")
    render_circle_track(output / "traj_canonical_circle_50hz.h")
    render_figure8_track(output / "traj_canonical_figure8_50hz.h")
    render_dronet_u_track(output / "traj_dronet_u_50hz.h")
    for track in CANONICAL_TRACKS:
        render_slow_track(track, output / f"traj_{track.name}_50hz.h")
    for track in TRACKS:
        render_track(track, output / f"traj_{track.name}_50hz.h")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
