/*
 * This file was autogenerated by TinyMPC on Wed Jan 21 10:03:31 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
