ccflags-y += -I$(OOT)/TinyMPC/include
ccflags-y += -I$(OOT)/TinyMPC/src
ccflags-y += -I$(OOT)/TinyMPC/src/tinympc
ccflags-y += -I$(src)

obj-y += out_of_tree_controller.o

# Prefer C++ compilation
$(obj)/out_of_tree_controller.o: $(src)/out_of_tree_controller.cpp