/*
 * This file was autogenerated by TinyMPC on Sat Jan 17 15:21:30 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
