/*
 * This file was autogenerated by TinyMPC on Mon Jan 19 14:25:32 2026
 */

#pragma once

#include "types.hpp"

#ifdef __cplusplus
extern "C" {
#endif

extern TinySolver tiny_solver;

#ifdef __cplusplus
}
#endif
